// Code generated by groq-modeler DO NOT EDIT.
//
// groq-modeler Version 1.0.0

package groq

// Endpoint is the endpoint for the groq api.
// string
type Endpoint string

// Model is the type for models present on the groq api.
// string
type Model string

const (
	completionsSuffix                     Endpoint = "/completions"
	chatCompletionsSuffix                 Endpoint = "/chat/completions"
	transcriptionsSuffix                  Endpoint = "/audio/transcriptions"
	translationsSuffix                    Endpoint = "/audio/translations"
	embeddingsSuffix                      Endpoint = "/embeddings"
	Gemma_7b_It                           Model    = "gemma-7b-it"
	Llama_Guard_3_8b                      Model    = "llama-guard-3-8b"
	Llama_3_1_8b_Instant                  Model    = "llama-3.1-8b-instant"
	Gemma2_9b_It                          Model    = "gemma2-9b-it"
	Mixtral_8x7b_32768                    Model    = "mixtral-8x7b-32768"
	Llama3_Groq_8b_8192_Tool_Use_Preview  Model    = "llama3-groq-8b-8192-tool-use-preview"
	Llava_V1_5_7b_4096_Preview            Model    = "llava-v1.5-7b-4096-preview"
	Whisper_Large_V3                      Model    = "whisper-large-v3"
	Llama_3_1_70b_Versatile               Model    = "llama-3.1-70b-versatile"
	Distil_Whisper_Large_V3_En            Model    = "distil-whisper-large-v3-en"
	Llama3_8b_8192                        Model    = "llama3-8b-8192"
	Llama3_70b_8192                       Model    = "llama3-70b-8192"
	Llama3_Groq_70b_8192_Tool_Use_Preview Model    = "llama3-groq-70b-8192-tool-use-preview"
)

// String returns the string representation of the Endpoint.
func (e Endpoint) String() string {
	return string(e)
}

var disabledModelsForEndpoints = map[Endpoint]map[Model]bool{
	completionsSuffix: {
		Whisper_Large_V3:           true,
		Distil_Whisper_Large_V3_En: true,
	},
	chatCompletionsSuffix: {
		Whisper_Large_V3:           true,
		Distil_Whisper_Large_V3_En: true,
	},
	transcriptionsSuffix: {
		Gemma_7b_It:                           true,
		Llama_Guard_3_8b:                      true,
		Llama_3_1_8b_Instant:                  true,
		Gemma2_9b_It:                          true,
		Mixtral_8x7b_32768:                    true,
		Llama3_Groq_8b_8192_Tool_Use_Preview:  true,
		Llava_V1_5_7b_4096_Preview:            true,
		Llama_3_1_70b_Versatile:               true,
		Llama3_8b_8192:                        true,
		Llama3_70b_8192:                       true,
		Llama3_Groq_70b_8192_Tool_Use_Preview: true,
	},
	translationsSuffix: {
		Gemma_7b_It:                           true,
		Llama_Guard_3_8b:                      true,
		Llama_3_1_8b_Instant:                  true,
		Gemma2_9b_It:                          true,
		Mixtral_8x7b_32768:                    true,
		Llama3_Groq_8b_8192_Tool_Use_Preview:  true,
		Llava_V1_5_7b_4096_Preview:            true,
		Llama_3_1_70b_Versatile:               true,
		Llama3_8b_8192:                        true,
		Llama3_70b_8192:                       true,
		Llama3_Groq_70b_8192_Tool_Use_Preview: true,
	},
}

func endpointSupportsModel(endpoint Endpoint, model Model) bool {
	return !disabledModelsForEndpoints[endpoint][model]
}
