// Code generated by groq-modeler DO NOT EDIT.
//
// Created at: 2024-12-16 09:24:38
//
// groq-modeler Version 1.1.2

package groq

type (
	// Model is a ai model accessible through the groq api.
	Model string

	// ChatModel is the type for chat models present on the groq api.
	ChatModel Model

	// ModerationModel is the type for moderation models present on the groq api.
	ModerationModel Model

	// AudioModel is the type for audio models present on the groq api.
	AudioModel Model
)

var (
	// ModelMixtral8X7B32768 is an AI text chat model.
	//
	// It is created/provided by Mistral AI.
	//
	// It has 32768 context window.
	//
	// It can be used with the following client methods:
	//	- CreateChatCompletion
	// 	- CreateChatCompletionStream
	// 	- CreateChatCompletionJSON
	ModelMixtral8X7B32768 ChatModel = "mixtral-8x7b-32768"
	// ModelDistilWhisperLargeV3En is an AI audio transcription model.
	//
	// It is created/provided by Hugging Face.
	//
	// It has 448 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelDistilWhisperLargeV3En AudioModel = "distil-whisper-large-v3-en"
	// ModelWhisperLargeV3 is an AI audio transcription model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 448 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelWhisperLargeV3 AudioModel = "whisper-large-v3"
	// ModelWhisperLargeV3Turbo is an AI audio transcription model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 448 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelWhisperLargeV3Turbo AudioModel = "whisper-large-v3-turbo"
)
